<a href="https://colab.research.google.com/github/04pys/ml-system-labs/blob/main/notebooks/lab03_03_nn_Module_and_class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#이전 세션까지는 선형 회귀 이해를 위해 hypothesis와 손실 함수를 직접 구현하여 사용하였다.
#이번 세션에서는 pytorch에서 이미 구현된 가설과 손실함수를 가져와서 사용하는법을 배운다

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [3]:
torch.manual_seed(1)

In [4]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])
#가져온 모델이 y=2x라는 정답을 잘 찾아낼 수 있도록 함

In [5]:
#nn.Linear()는 입력의 차원, 출력의 차원을 인수로 받습니다.
# 모델을 선언 및 초기화. 단순 선형 회귀이므로 input_dim=1, output_dim=1.
model = nn.Linear(1, 1) #하나의 입력에 대해서 하나의 출력을 가지므로, 입력 차원과 출력 차원 모두 1을 인수로 사용하였습니다.

In [6]:
print(list(model.parameters())) # 첫번째 값이 w고 두번째 값이 b이다. 초기값이 랜덤 설정됨. 둘다 학습에 사용되므로 requires_grad=True(backward실행시 둘다 각각 미분됨)

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [7]:
# optimizer 설정. 경사 하강법 SGD를 사용하고 learning rate를 의미하는 lr은 0.01
optimizer = torch.optim.SGD(model.parameters(), lr=0.01) # model의 parameters인 w,b가 들어간다

In [8]:
nb_epochs = 2000
for epoch in range(nb_epochs + 1):
  #H(x) 계산
  prediction = model(x_train) # prediction은 hypothesis와 같은걸 의미한다

  #cost 계산
  cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

  # cost로 H(x) 개선하는 부분(경사하강법)
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()


  if epoch % 100 == 0:
    # 100번마다 로그 출력
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, cost.item()
    ))

Epoch    0/2000 Cost: 13.103541
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


In [9]:
# 임의의 입력 4를 선언
new_var =  torch.FloatTensor([[4.0]])
# 입력한 값 4에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) # forward 연산
# y = 2x 이므로 입력이 4라면 y가 8에 가까운 값이 나와야 제대로 학습이 된 것
print("훈련 후 입력이 4일 때의 예측값 :", pred_y)

훈련 후 입력이 4일 때의 예측값 : tensor([[7.9989]], grad_fn=<AddmmBackward0>)


In [10]:
#학습 후 w와 b 출력
print(list(model.parameters())) #w = 2, b = 0에 가깝게 나오게 된다. 정답에 가까움.

[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


In [11]:
#다중 선형회귀 구현하기

In [12]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [13]:
torch.manual_seed(1)

In [14]:
#3개의 x로 하나의 y를 예측하는 문제

In [15]:
# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [21]:
# 모델을 선언 및 초기화. 다중 선형 회귀이므로 input_dim=3, output_dim=1.
#input_dim 은 x가 3개이므로 3, y는 하나
#model = (3x1) 크기의 W와 (1x1) 크기의 b를 가지는 선형회귀 모델.
model = nn.Linear(3, 1)

In [17]:
print(list(model.parameters())) # 첫번째는 랜덤 w 3개, 2번째는 랜덤 b 한개. 전부 미분에 이용되기에 requires_grad = True

[Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119]], requires_grad=True), Parameter containing:
tensor([0.2710], requires_grad=True)]


In [24]:
#lr = 0.01이면 기울기가 발산함.
#궁금해서 해봄 ㅎㅎ
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)
nb_epochs = 2000
for epoch in range(nb_epochs+1):

  #H(x) 계산(hypothesis)
  prediction = model(x_train)
  # model(x_train)은 model.forward(x_train)와 동일함.

  #cost 계산(손실함수)
  cost = F.mse_loss(prediction, y_train)


  # cost로 H(x) 개선하는 부분
  # gradient를 0으로 초기화
  optimizer.zero_grad()
  # 비용 함수를 미분하여 gradient 계산
  cost.backward()
  # W와 b를 업데이트
  optimizer.step()

  if epoch % 100 == 0:
  # 100번마다 로그 출력
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, cost.item()
    ))

Epoch    0/2000 Cost: 4.328986
Epoch  100/2000 Cost: nan
Epoch  200/2000 Cost: nan
Epoch  300/2000 Cost: nan
Epoch  400/2000 Cost: nan
Epoch  500/2000 Cost: nan
Epoch  600/2000 Cost: nan
Epoch  700/2000 Cost: nan
Epoch  800/2000 Cost: nan
Epoch  900/2000 Cost: nan
Epoch 1000/2000 Cost: nan
Epoch 1100/2000 Cost: nan
Epoch 1200/2000 Cost: nan
Epoch 1300/2000 Cost: nan
Epoch 1400/2000 Cost: nan
Epoch 1500/2000 Cost: nan
Epoch 1600/2000 Cost: nan
Epoch 1700/2000 Cost: nan
Epoch 1800/2000 Cost: nan
Epoch 1900/2000 Cost: nan
Epoch 2000/2000 Cost: nan


In [19]:
# 위 결과는 learning rate를 0.01로 둬서 cost값이 발산함.(cost를 w,b로 미분한 값에 0.01을 곱해서 w,b에서 빼도 원래의 w,b값보다 cost의 순간변화율(미분값)의 절댓값이 커지게 만듦 )

In [25]:
print(list(model.parameters()))

[Parameter containing:
tensor([[nan, nan, nan]], requires_grad=True), Parameter containing:
tensor([nan], requires_grad=True)]


In [31]:
# 모델을 선언 및 초기화. 다중 선형 회귀이므로 input_dim=3, output_dim=1.
#input_dim 은 x가 3개이므로 3, y는 하나
#model = (3x1) 크기의 W와 (1x1) 크기의 b를 가지는 선형회귀 모델.
model = nn.Linear(3, 1)

In [32]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)
nb_epochs = 2000
for epoch in range(nb_epochs+1):

  #H(x) 계산(hypothesis)
  prediction = model(x_train)
  # model(x_train)은 model.forward(x_train)와 동일함.

  #cost 계산(손실함수)
  cost = F.mse_loss(prediction, y_train)


  # cost로 H(x) 개선하는 부분
  # gradient를 0으로 초기화
  optimizer.zero_grad()
  # 비용 함수를 미분하여 gradient 계산
  cost.backward()
  # W와 b를 업데이트
  optimizer.step()

  if epoch % 100 == 0:
  # 100번마다 로그 출력
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, cost.item()
    ))

Epoch    0/2000 Cost: 31362.458984
Epoch  100/2000 Cost: 0.267419
Epoch  200/2000 Cost: 0.266823
Epoch  300/2000 Cost: 0.266239
Epoch  400/2000 Cost: 0.265651
Epoch  500/2000 Cost: 0.265086
Epoch  600/2000 Cost: 0.264524
Epoch  700/2000 Cost: 0.263962
Epoch  800/2000 Cost: 0.263412
Epoch  900/2000 Cost: 0.262871
Epoch 1000/2000 Cost: 0.262337
Epoch 1100/2000 Cost: 0.261808
Epoch 1200/2000 Cost: 0.261285
Epoch 1300/2000 Cost: 0.260773
Epoch 1400/2000 Cost: 0.260260
Epoch 1500/2000 Cost: 0.259755
Epoch 1600/2000 Cost: 0.259250
Epoch 1700/2000 Cost: 0.258762
Epoch 1800/2000 Cost: 0.258269
Epoch 1900/2000 Cost: 0.257777
Epoch 2000/2000 Cost: 0.257306


In [33]:
# 임의의 입력 [73, 80, 75]를 선언
new_var =  torch.FloatTensor([[73, 80, 75]])
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var)
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y)

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[151.3034]], grad_fn=<AddmmBackward0>)


In [34]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.9083, 0.4603, 0.6429]], requires_grad=True), Parameter containing:
tensor([-0.0421], requires_grad=True)]


In [35]:
#모델을 클래스로 구현하기. pytorch의 구현체들은 대부분 모델을 클래스로 구현하고 있다

In [38]:
# 모델을 선언 및 초기화. 단순 선형 회귀이므로 input_dim=1, output_dim=1. 기본 모델 구현
model = nn.Linear(1, 1)

In [41]:
#위에서 구현한 모델을 클래스로 구현
class LinearRegressionModel(nn.Module): # torch.nn.Module을 상속받는 파이썬 클래스
  def __init__(self): # 모델의 생성자
    super().__init__() # nn.Module 클래스의 속성들을 가지고 초기화됨.
    self.linear = nn.Linear(1, 1) # 단순 선형 회귀이므로 input_dim=1, output_dim=1.

  def forward(self, x): # model(x_train) 처럼 데이터와 함께 이 클래스의 객체를 호출하면 forward함수 자동으로 실행됨
    return self.linear(x)

In [42]:
model = LinearRegressionModel()

In [43]:
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1) # 다중 선형 회귀이므로 input_dim=3, output_dim=1.

    def forward(self, x):
        return self.linear(x)

In [ ]:
#선형회귀 클래스로 구현

In [44]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [45]:
torch.manual_seed(1)

In [46]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [55]:
class LinearRegressionModel(nn.Module): # torch.nn.Module을 상속받는 파이썬 클래스
  def __init__(self): # 모델의 생성자
    super().__init__() # nn.Module 클래스의 속성들을 가지고 초기화됨.
    self.linear = nn.Linear(1, 1) # 단순 선형 회귀이므로 input_dim=1, output_dim=1.

  def forward(self, x): # model(x_train) 처럼 데이터와 함께 이 클래스의 객체를 호출하면 forward함수 자동으로 실행됨
    return self.linear(x)

In [47]:
momdel = LinearRegressionModel()

In [48]:
optimizer = torch.optim.SGD(model.parameters(), lr = 0.01)

In [49]:
# 전체 훈련 데이터에 대해 경사 하강법을 2,000회 반복
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward() # backward 연산
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 24.685446
Epoch  100/2000 Cost: 0.071069
Epoch  200/2000 Cost: 0.043916
Epoch  300/2000 Cost: 0.027138
Epoch  400/2000 Cost: 0.016769
Epoch  500/2000 Cost: 0.010362
Epoch  600/2000 Cost: 0.006403
Epoch  700/2000 Cost: 0.003957
Epoch  800/2000 Cost: 0.002445
Epoch  900/2000 Cost: 0.001511
Epoch 1000/2000 Cost: 0.000934
Epoch 1100/2000 Cost: 0.000577
Epoch 1200/2000 Cost: 0.000357
Epoch 1300/2000 Cost: 0.000220
Epoch 1400/2000 Cost: 0.000136
Epoch 1500/2000 Cost: 0.000084
Epoch 1600/2000 Cost: 0.000052
Epoch 1700/2000 Cost: 0.000032
Epoch 1800/2000 Cost: 0.000020
Epoch 1900/2000 Cost: 0.000012
Epoch 2000/2000 Cost: 0.000008


In [50]:
#다중 선형회귀 클래스로 구현

In [51]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [52]:
torch.manual_seed(1)

In [53]:
# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [54]:
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1) # 다중 선형 회귀이므로 input_dim=3, output_dim=1.

    def forward(self, x):
        return self.linear(x)

model = MultivariateLinearRegressionModel()

In [56]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [57]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)
    # model(x_train)은 model.forward(x_train)와 동일함.

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward()
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 31667.597656
Epoch  100/2000 Cost: 0.225993
Epoch  200/2000 Cost: 0.223911
Epoch  300/2000 Cost: 0.221941
Epoch  400/2000 Cost: 0.220059
Epoch  500/2000 Cost: 0.218271
Epoch  600/2000 Cost: 0.216575
Epoch  700/2000 Cost: 0.214950
Epoch  800/2000 Cost: 0.213413
Epoch  900/2000 Cost: 0.211952
Epoch 1000/2000 Cost: 0.210560
Epoch 1100/2000 Cost: 0.209232
Epoch 1200/2000 Cost: 0.207967
Epoch 1300/2000 Cost: 0.206761
Epoch 1400/2000 Cost: 0.205619
Epoch 1500/2000 Cost: 0.204522
Epoch 1600/2000 Cost: 0.203484
Epoch 1700/2000 Cost: 0.202485
Epoch 1800/2000 Cost: 0.201542
Epoch 1900/2000 Cost: 0.200635
Epoch 2000/2000 Cost: 0.199769
