<a href="https://colab.research.google.com/github/04pys/ml-system-labs/blob/main/notebooks/lab04_02_Logistic_Regression_with_nn_Module_and_class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# nn.sigmoid를 이용한 Logistic Regression 구현

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [3]:
torch.manual_seed(1)

In [4]:
x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

In [8]:
model = nn.Sequential(
    nn.Linear(2, 1),
    nn.Sigmoid()
)

In [9]:
model(x_train)

tensor([[0.3600],
        [0.2872],
        [0.6801],
        [0.4389],
        [0.5216],
        [0.7473]], grad_fn=<SigmoidBackward0>)

In [11]:
optimizer = optim.SGD(model.parameters(), lr = 1)

nb_epochs = 1000

for epoch in range(nb_epochs+1):
  #H(x) 계산
  hypothesis = model(x_train)

  #cost 계산
  cost = F.binary_cross_entropy(hypothesis, y_train)

  #경사하강법
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

   # 20번마다 로그 출력
  if epoch % 10 == 0:
      prediction = hypothesis >= torch.FloatTensor([0.5]) # 예측값이 0.5를 넘으면 True로 간주
      correct_prediction = prediction.float() == y_train # 실제값과 일치하는 경우만 True로 간주
      accuracy = correct_prediction.sum().item() / len(correct_prediction) # 정확도를 계산
      print('Epoch {:4d}/{} Cost: {:.6f} Accuracy {:2.2f}%'.format( # 각 에포크마다 정확도를 출력
          epoch, nb_epochs, cost.item(), accuracy * 100,
      ))

Epoch    0/1000 Cost: 0.614994 Accuracy 66.67%
Epoch   10/1000 Cost: 0.747550 Accuracy 83.33%
Epoch   20/1000 Cost: 0.633216 Accuracy 83.33%
Epoch   30/1000 Cost: 0.538123 Accuracy 83.33%
Epoch   40/1000 Cost: 0.450406 Accuracy 83.33%
Epoch   50/1000 Cost: 0.366382 Accuracy 83.33%
Epoch   60/1000 Cost: 0.287368 Accuracy 83.33%
Epoch   70/1000 Cost: 0.219289 Accuracy 83.33%
Epoch   80/1000 Cost: 0.173225 Accuracy 100.00%
Epoch   90/1000 Cost: 0.151674 Accuracy 100.00%
Epoch  100/1000 Cost: 0.140280 Accuracy 100.00%
Epoch  110/1000 Cost: 0.131002 Accuracy 100.00%
Epoch  120/1000 Cost: 0.122903 Accuracy 100.00%
Epoch  130/1000 Cost: 0.115765 Accuracy 100.00%
Epoch  140/1000 Cost: 0.109426 Accuracy 100.00%
Epoch  150/1000 Cost: 0.103760 Accuracy 100.00%
Epoch  160/1000 Cost: 0.098664 Accuracy 100.00%
Epoch  170/1000 Cost: 0.094056 Accuracy 100.00%
Epoch  180/1000 Cost: 0.089870 Accuracy 100.00%
Epoch  190/1000 Cost: 0.086050 Accuracy 100.00%
Epoch  200/1000 Cost: 0.082549 Accuracy 100.00%


In [12]:
model(x_train) # 0 0 0 1 1 1 이 나와야 가장 정확함

tensor([[2.8020e-04],
        [3.1770e-02],
        [3.9191e-02],
        [9.5600e-01],
        [9.9821e-01],
        [9.9968e-01]], grad_fn=<SigmoidBackward0>)

In [13]:
print(list(model.parameters()))

[Parameter containing:
tensor([[3.2477, 1.5151]], requires_grad=True), Parameter containing:
tensor([-14.4576], requires_grad=True)]


In [14]:
# 이제 이 모델을 class로 구현해볼것임

In [16]:
x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

In [21]:
class BinaryClassifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(2, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        return self.sigmoid(self.linear(x))

In [22]:
model = BinaryClassifier()

In [23]:
model(x_train)

tensor([[0.4147],
        [0.4105],
        [0.6101],
        [0.5386],
        [0.6018],
        [0.7205]], grad_fn=<SigmoidBackward0>)

In [24]:
optimizer = optim.SGD(model.parameters(), lr = 1)

nb_epochs = 1000
for epoch in range(nb_epochs+1):
  hypothesis = model(x_train)

  cost = F.binary_cross_entropy(hypothesis, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

   # 20번마다 로그 출력
  if epoch % 10 == 0:
    prediction = hypothesis >= torch.FloatTensor([0.5]) # 예측값이 0.5를 넘으면 True로 간주
    correct_prediction = prediction.float() == y_train # 실제값과 일치하는 경우만 True로 간주
    accuracy = correct_prediction.sum().item() / len(correct_prediction) # 정확도를 계산
    print('Epoch {:4d}/{} Cost: {:.6f} Accuracy {:2.2f}%'.format( # 각 에포크마다 정확도를 출력
        epoch, nb_epochs, cost.item(), accuracy * 100,
    ))

Epoch    0/1000 Cost: 0.576740 Accuracy 83.33%
Epoch   10/1000 Cost: 0.818109 Accuracy 66.67%
Epoch   20/1000 Cost: 0.582192 Accuracy 83.33%
Epoch   30/1000 Cost: 0.488437 Accuracy 83.33%
Epoch   40/1000 Cost: 0.402663 Accuracy 83.33%
Epoch   50/1000 Cost: 0.321072 Accuracy 83.33%
Epoch   60/1000 Cost: 0.247059 Accuracy 83.33%
Epoch   70/1000 Cost: 0.190018 Accuracy 100.00%
Epoch   80/1000 Cost: 0.158865 Accuracy 100.00%
Epoch   90/1000 Cost: 0.144834 Accuracy 100.00%
Epoch  100/1000 Cost: 0.134897 Accuracy 100.00%
Epoch  110/1000 Cost: 0.126315 Accuracy 100.00%
Epoch  120/1000 Cost: 0.118780 Accuracy 100.00%
Epoch  130/1000 Cost: 0.112109 Accuracy 100.00%
Epoch  140/1000 Cost: 0.106162 Accuracy 100.00%
Epoch  150/1000 Cost: 0.100828 Accuracy 100.00%
Epoch  160/1000 Cost: 0.096016 Accuracy 100.00%
Epoch  170/1000 Cost: 0.091653 Accuracy 100.00%
Epoch  180/1000 Cost: 0.087679 Accuracy 100.00%
Epoch  190/1000 Cost: 0.084043 Accuracy 100.00%
Epoch  200/1000 Cost: 0.080704 Accuracy 100.00%

In [25]:
model(x_train)

tensor([[2.7660e-04],
        [3.1613e-02],
        [3.8984e-02],
        [9.5621e-01],
        [9.9823e-01],
        [9.9969e-01]], grad_fn=<SigmoidBackward0>)

In [27]:
print(list(model.parameters()))

[Parameter containing:
tensor([[3.2528, 1.5178]], requires_grad=True), Parameter containing:
tensor([-14.4811], requires_grad=True)]
