<a href="https://colab.research.google.com/github/04pys/ml-system-labs/blob/main/notebooks/lab1_tensor_manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#pytorch 기초 중 tensor_manipulation에 대해 배워보는 시간이다.

In [ ]:
#우선 numpy로 텐서를 생성해보고 pytorch 실습으로 넘어간다

In [3]:
import numpy as np

In [ ]:
t = np.array([0., 1., 2., 3., 4., 5., 6])
# 파이썬으로 설명하면 List를 생성해서 np.array로 1차원 array로 변환함.
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [ ]:
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  1
Shape of t:  (7,)


In [ ]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1]) # 인덱스를 통한 원소 접근
# -1은 뒤에서부터 시작되는 인덱스

t[0] t[1] t[-1] =  0.0 1.0 6.0


In [ ]:
print('t[2:5] t[4:-1]  = ', t[2:5], t[4:-1]) # [시작 번호 : 끝 번호]로 범위 지정을 통해 가져온다.
#이때, 끝번호는 포함하지 않는다 (주의!!)

t[2:5] t[4:-1]  =  [2. 3. 4.] [4. 5.]


In [ ]:
print('t[:2] t[3:]     = ', t[:2], t[3:]) # 시작 번호를 생략한 경우와 끝 번호를 생략한 경우
#시작을 생략했을경우 처음부터 끝까지(끝 인덱스는 포함 안함)
#끝을 생략했을 경우 시작부터 마지막 인덱스까지

t[:2] t[3:]     =  [0. 1.] [3. 4. 5. 6.]


In [ ]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [ ]:
print(t[:, 1]) # 첫번째 차원을 전체 선택한 상황에서 두번째 차원의 첫번째 것만 가져온다.
#위 경우는 numpy일때인데, t가 torch로 선언된 경우에도 동일한 결과가 나온다

[ 2.  5.  8. 11.]


In [ ]:
print('Rank  of t: ', t.ndim) # 2
print('Shape of t: ', t.shape) # (4,3) 즉 4행 3열

Rank  of t:  2
Shape of t:  (4, 3)


In [ ]:
#pytorch 실습

In [4]:
import torch

In [ ]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [ ]:
print(t.dim())
print(t.shape)
print(t.size())

# dim(), size() 와는 다르게 shape는 괄호를 안쓰는것 주의!

1
torch.Size([7])
torch.Size([7])


In [ ]:
print(t[0], t[1], t[-1])  # 인덱스로 접근
print(t[2:5], t[4:-1])    # 슬라이싱
print(t[:2], t[3:])       # 슬라이싱
#numpy와 동일

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [ ]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                       ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [ ]:
print(t.dim())
print(t.shape)
print(t.size())

2
torch.Size([4, 3])
torch.Size([4, 3])


In [ ]:
print(t[:, 1]) # 첫번째 차원을 전체 선택한 상황에서 두번째 차원의 첫번째 것만 가져온다.
print(t[:, 1].size()) # ↑ 위의 경우의 크기

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


In [ ]:
print(t[:, :-1])

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [ ]:
#Broadcasting

In [ ]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [ ]:
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # [3] -> [3, 3]으로 broadcasting 발생
print(m1 + m2)

tensor([[4., 5.]])


In [ ]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


In [ ]:
#행렬의 곱셈

In [ ]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print("Shape of Matrix 1: ", m1.shape) # 2 x 2
print("Shape of Matrix 2: ", m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

# print(m2.matmul(m1))는 안되는 이유: matmul하려면 첫번째 행렬의 열 개수와 두번째 행렬의 행 개수가 같아야 함

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [ ]:
# element-wise 곱셈. 같은 크기의 행렬일경우 원소끼리 곱셈 수행
#다른 크기의 행렬일경우 Broadcasting 발생
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2))

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [ ]:
# 브로드캐스팅 과정에서 m2 텐서가 어떻게 변경되는지 보겠습니다.
'''[1]
[2]
==> [[1, 1],
     [2, 2]]
'''

'[1]\n[2]\n==> [[1, 1],\n     [2, 2]]\n'

In [ ]:
#Mean(평균)

In [ ]:
t = torch.FloatTensor([[1, 2]])
print(t.mean())

tensor(1.5000)


In [ ]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)


tensor([[1., 2.],
        [3., 4.]])


In [ ]:
print(t.mean())

tensor(2.5000)


In [ ]:
print(t.mean(dim=0))
# dim=0이라는건 첫번째 차원을 의미
#행렬에서 첫번째 차원은 행, 두번째 차원은 열이다
#mean의 인자로 dim=0을 주는건 dim=0인 첫번째 차원을 제거하겠다는 뜻이다. 즉 2x2 -> 1x2로 차원을 바꾼다
#첫번째 열의 평균을 구하고, 두번째 열의 평균을 구한다

tensor([2., 3.])


In [ ]:
print(t.mean(dim=1))
#dim=1 즉 두번째 차원, 열을 제거하고 평균을 구하겠다는 의미
#첫번째 행의 평균을 구하고, 두번째 행의 평균을 구한다
#1.5, 3.5

tensor([1.5000, 3.5000])


In [ ]:
print(t.mean(dim=-1))
#마지막 차원을 제거한다는 뜻.
#이경우 열을 제거하겠다는것과 동일(dim=1과 동일)

In [1]:
#덧셈

In [5]:
t = torch.FloatTensor([[1, 2], [3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [6]:
print(t.sum())
print(t.sum(dim=0)) # 행을 제거, 열끼리 덧셈
print(t.sum(dim=1)) # 열을 제거, 행끼리 덧셈
print(t.sum(dim=-1)) # 맨 마지막 차원을 제거(여기선 열 제거, 행끼리 덧셈)

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [7]:
#max, argmax

In [8]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [9]:
print(t.max()) # Returns one value: max

tensor(4.)


In [10]:
print(t.max(dim=0)) # Returns two values: max and argmax
#dim = 0이므로 첫번째 차원(행) 제거, dim 인자를 줄 경우엔 max와 함께 argmax도 출력
#각 열의 max인 3,4의 해당 열에서의 인덱스는 둘다 1이기 때문에 argmax가 1,1로 출력된다

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [11]:
print("Max: ", t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [12]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


In [13]:
# 뷰(View) - 원소의 수를 유지하면서 텐서의 크기 변경. 매우 중요!

In [14]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)

In [15]:
print(ft.shape)

torch.Size([2, 2, 3])


In [18]:
print(ft.view([-1, 3]))
print(ft.view([-1, 3]).shape)
# -1,3이라는것은 첫번째 차원은 사용자가 잘 모르겠으니 두번째 차원의 크기를 3으로 하라는 뜻.
# 즉, (n,3) 크기의 2차원 행렬이 만들어짐
# 2 x 2 x 3의 크기에서 4 x 3 크기의 행렬로 크기 변경
#view는 기본적으로 변경 전과 변경 후의 텐서 안의 원소의 개수가 유지되어야 합니다.
#파이토치의 view는 사이즈가 -1로 설정되면 다른 차원으로부터 해당 값을 유추합니다.

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [19]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [20]:
#스퀴즈(Squeeze) - 1인 차원을 제거한다.

In [22]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)

tensor([[0.],
        [1.],
        [2.]])


In [24]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [25]:
#언스퀴즈(Unsqueeze) - 특정 위치에 1인 차원을 추가한다.

In [27]:
ft = torch.FloatTensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [32]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [31]:
print(ft.view([1, -1])) # 1, n의 크기를 가지는 2차원 텐서로 재배치해라. 여기선 1, 3이 된다
print(ft.view([1, -1]).shape) # ft.unsqueeze(0)과 똑같은 역할

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [33]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [34]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [35]:
#view(), squeeze(), unsqueeze()는 텐서의 원소 수를 그대로 유지하면서 모양과 차원을 조절합니다.

In [36]:
# 타입 캐스팅(Type Casting)

In [37]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [38]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [39]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [40]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


In [41]:
#연결하기(concatenate)

In [42]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [44]:
print(torch.cat([x, y], dim=0)) # 첫번째 차원(행)으로 확장
# 2 x 2 -> 4 x 2로 확장

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [45]:
print(torch.cat([x, y], dim=1))

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [46]:
# 스택킹(Stacking)

In [47]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [48]:
print(torch.stack([x, y, z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [50]:
#stacking과 똑같은 작업
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [51]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=1)) # dim=1을 하면 열 차원으로 확장, 1, 2 세개가 모여서 1,6됨

tensor([[1., 4., 2., 5., 3., 6.]])


In [52]:
print(torch.stack([x, y, z], dim=1)) #두번째 차원이 증가하도록 stacking. x, y, z가 열 방향으로 쌓였다

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [53]:
# ones_like와 zeros_like - 0으로 채워진 텐서와 1로 채워진 텐서

In [55]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [56]:
print(torch.ones_like(x)) # 입력 텐서와 크기를 동일하게 하면서 값을 1로 채우기

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [57]:
print(torch.zeros_like(x)) # 입력 텐서와 크기를 동일하게 하면서 값을 0로 채우기

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [58]:
# In-place Operation (덮어쓰기 연산)

In [59]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [60]:
print(x.mul(2)) # 곱하기 2를 수행한 결과를 변수 x에 값을 저장하면서 결과를 출력
print(x) # 기존의 값 출력

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [61]:
print(x.mul_(2)) # 연산 뒤에다 언더바(_) 붙이면 연산 수행후 덮어쓰기 실행
print(x) # 원래 x 출력해보면 덮어씌어진것 확인할 수 있음

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
